"""Run a deterministic subset of pytest's collected tests without new dependencies.

Example: python tools/ci_pytest_shard.py --shard 1 --shards 3 -- -v --maxfail=1
Normal pytest filters run before sharding; collection order within a shard is kept.
Every parametrized function stays together, even when its labels vary at collection.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from collections import Counter
from pathlib import Path

import pytest


def partition_nodeids(nodeids: list[str], shard_count: int) -> list[list[str]]:
    if shard_count < 1:
        raise ValueError("shard count must be positive")
    if len(set(nodeids)) != len(nodeids):
        raise ValueError("duplicate collected node IDs prevent an exact shard partition")
    partitions: list[list[str]] = [[] for _ in range(shard_count)]
    for nodeid in nodeids:
        # Automatic parameter labels can contain generated bytes/timestamps.
        # Only the unparametrized identity is stable across independent runners.
        identity = nodeid.split("[", 1)[0]
        digest = hashlib.sha256(identity.encode("utf-8")).digest()
        partitions[int.from_bytes(digest, "big") % shard_count].append(nodeid)
    # Keep the coverage invariant explicit: every collected node occurs once.
    if Counter(node for part in partitions for node in part) != Counter(nodeids):
        raise ValueError("shard partition lost or duplicated collected nodes")
    return partitions


class ShardSelection:
    def __init__(self, shard: int, shard_count: int) -> None:
        if not 1 <= shard <= shard_count:
            raise ValueError("shard must be between 1 and the shard count")
        self.shard = shard
        self.shard_count = shard_count

    @pytest.hookimpl(trylast=True)
    def pytest_collection_modifyitems(self, config, items) -> None:
        # pytest's --deselect/-k/-m filters must run before this final partition.
        try:
            partitions = partition_nodeids([item.nodeid for item in items], self.shard_count)
        except ValueError as exc:
            raise pytest.UsageError(str(exc)) from exc
        selected_ids = set(partitions[self.shard - 1])
        deselected = [item for item in items if item.nodeid not in selected_ids]
        total = len(items)
        items[:] = [item for item in items if item.nodeid in selected_ids]
        if deselected:
            config.hook.pytest_deselected(items=deselected)
        reporter = config.pluginmanager.get_plugin("terminalreporter")
        if reporter is not None:
            sizes = ", ".join(str(len(part)) for part in partitions)
            reporter.write_line(
                f"CI shard {self.shard}/{self.shard_count}: selected {len(items)}/{total} "
                f"filtered collected nodes; exact disjoint partition sizes: [{sizes}]"
            )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--shard", type=int, required=True, help="one-based shard index")
    parser.add_argument("--shards", type=int, required=True, help="total number of shards")
    args, pytest_args = parser.parse_known_args(argv)
    try:
        selection = ShardSelection(args.shard, args.shards)
    except ValueError as exc:
        parser.error(str(exc))
    if pytest_args[:1] == ["--"]:
        pytest_args = pytest_args[1:]
    # Match `python -m pytest`: the working directory is importable, not just tools/.
    sys.path.insert(0, str(Path.cwd()))
    return int(pytest.main(pytest_args, plugins=[selection]))


if __name__ == "__main__":
    raise SystemExit(main())
